services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app

  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app

networks:
  app:
    driver: bridge
