services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=graphql
      - POSTGRES_USER=graphql
      - POSTGRES_DB=graphql
    networks:
      - app

  backend:
    image: 21hmzz/21hmzz-nestapp-backend
    ports:
      - "3000:3000"
    networks:
      - app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=graphql
      - POSTGRES_PASSWORD=graphql
      - POSTGRES_DB=graphql
    depends_on:
      - redis
      - postgres

  frontend:
    image: 21hmzz/21hmzz-nestapp-frontend
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - backend
    command: [ "sh", "-c", "npm run generate && npm run dev" ]

networks:
  app:
    driver: bridge
