name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/21hmzz-nestapp-backend:latest

      - name: Show Backend image digest
        run: echo ${{ steps.build.outputs.digest }}

      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/21hmzz-nestapp-frontend:latest

      - name: Show Frontend image digest
        run: echo ${{ steps.build.outputs.digest }}
