name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Etape 1
        uses: actions/checkout@v2

      - name: Etape 2
        uses: docker/setup-buildx-action@v1

      - name: Log docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build/Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/21hmzz-nestapp:latest

      - name: Digest
        run: echo ${{ steps.build-push.outputs.digest }}
